### Obtener todos los países

GET http://localhost:3000/paises


### Obtener los datos de un país en particular (ejemplo: Colombia)

GET http://localhost:3000/paises/Colombia


### Obtener todos los países que hablen un idioma específico (ejemplo: italiano)

GET http://localhost:3000/paises?idioma=italiano


### Insertar un nuevo país

POST http://localhost:3000/paises

Content-Type: application/json


{

  "pais": "Argentina",

  "idioma": ["Español"],

  "continente": "América"

}


### Borrar un país (ejemplo: Argentina)

DELETE http://localhost:3000/paises/Argentina